Repository thales-markets/contracts, pull requests merged in 2022-12, with the labels that each got.

#248 - refreshed deployments OP goerli
  scripts/deployments.json
Labels: parlay

#252 Increase parlays size and riskPerGame combination
  .openzeppelin/unknown-10.json
  .openzeppelin/unknown-420.json
  contracts/SportMarkets/Parlay/ParlayMarketsAMM.sol
  contracts/SportMarkets/Parlay/ParlayVerifier.sol
  contracts/interfaces/IParlayMarketsAMM.sol
  scripts/abi/IParlayMarketsAMM.json
  scripts/abi/ParlayMarketsAMM.json
  scripts/abi/ParlayVerifier.json
  scripts/deploySportMarkets/deployParlayAMM/deploy_ParlayVerifier.js
  scripts/deployments.json
  test/contracts/SportMarkets/ParlayAMM.js
Labels: overtime, parlay

#254 added methods for whitelist to setBookmakerIdsBySportId
  .openzeppelin/unknown-10.json
  .openzeppelin/unknown-420.json
  contracts/SportMarkets/Rundown/TherundownConsumerVerifier.sol
  scripts/abi/TherundownConsumerVerifier.json
  scripts/deployments.json
  test/contracts/SportMarkets/TherundownConsumerVerifier.js
Labels: overtime
